name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4  # Checkout the code from the repository

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0  # Specify the version of Terraform you want to use

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key ID
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key
          aws-region: ${{ secrets.AWS_REGION }}  # The AWS region for provisioning infrastructure

      - name: Terraform Init
        run: terraform init  # Initializes the Terraform configuration and downloads providers

      - name: Terraform Validate
        run: terraform validate  # Validate the Terraform configuration files

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan  # Generate an execution plan for Terraform
        continue-on-error: true  # Continue running even if the plan fails (used for subsequent check)

      - name: Check Terraform Plan
        run: |
          if [ ${{ steps.plan.outcome }} != "success" ]; then
            echo "Terraform plan failed"
            exit 1  # Exit the workflow if the plan failed
          fi

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan  # Apply the Terraform plan to provision resources
